### ISSUE TITLE
Marked result text disappears when the theme is changed while calculator is open

### ISSUE THREAD

**Issue by sthivaios** [microsoft/calculator#2349]
**Describe the bug**
Consider you do some calculation and then you select the text in the answer. If the "windows-wide" theme is changed from light to dark or vice versa, the selected text disappears (or perhaps turns the same color as the selection?).

**Steps To Reproduce**
1. Open the calculator app
2. Do some calculation
3. Select the text in the answer
4. Open the Windows settings app and change the theme from light to dark
5. Go back to the calculator app. The selected text is now gone.

**Expected behavior**
Of course, that the text would not disappear.

**Screenshots**

![Image](https://github.com/user-attachments/assets/658ac282-0836-46ca-9a6c-7166ec1aeb2b)
![Image](https://github.com/user-attachments/assets/365085f9-544d-420c-8b30-6c2a81e9c720)
![Image](https://github.com/user-attachments/assets/74808040-61a4-418f-90c3-afe64ce25e84)

**Device and Application Information**
 - OS Build: 10.0.26100.0
 - Architecture: X64
 - Application Version: 11.2502.2.0
 - Region: en-001
 - Dev Version Installed: False
 
**Additional context**
\-

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

**Comment by Ayush41** [comment]
I just checked this on the latest version of the Calculator app, and I couldn't reproduce the issue — the selected result text remains visible after switching between light and dark themes.

Seems like this might have already been fixed in a recent update. Could someone from the team confirm if it's okay to close this?

**Comment by sthivaios** [comment]
> I just checked this on the latest version of the Calculator app, and I couldn't reproduce the issue — the selected result text remains visible after switching between light and dark themes.
> 
> Seems like this might have already been fixed in a recent update. Could someone from the team confirm if it's okay to close this?

Looks like there are no releases here on GitHub to check if this is the latest version, but according to the Microsoft store, yes I _do_ have the latest one. Not sure whether I was on this version when I created this issue, but I can confirm it still happens now.

For reference this is: `11.2502.2.0`
